<?xml version="1.0" encoding="utf-8"?><Database Name="CrudWindowsForms" Class="PersonasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=CrudWindowsForms;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="CrudWindowsFormsLinq.Properties.Settings" SettingsPropertyName="CrudWindowsFormsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.People" Member="Person">
    <Type Name="Person">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>